### ISSUE TITLE
Intendo

### ISSUE THREAD

**Issue by BB1464** [rich-iannone/intendo#1]
Hi @rich-iannone, can you please help fix the connection issues to your package, I can not install it on my system, I am using windows. Below is the error message

remotes::install_github("rich-iannone/intendo")
Downloading GitHub repo rich-iannone/intendo@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/rich-iannone/intendo/tarball/HEAD' failed

**Comment by jlslu** [comment]
Im having the same issue as well. Did you ever get this resolved ?

**Comment by BB1464** [comment]
@jlslu this issue has not been resolved.

**Comment by rich-iannone** [comment]
@BB1464 @jlslu Sorry for taking so long to get to this. It's a pretty serious issue so I'm going to look at a better solution for downloading. I might even include the smaller datasets in the package and only require that the larger datasets be retrieved from GitHub.

**Comment by jlslu** [comment]
@rich-iannone Thanks I ended up manually downloading from your page and loading up in R Studio. Thanks for responding

**Comment by rich-iannone** [comment]
Now that this is on CRAN, installing shouldn't be a problem any more. Thanks for your patience on all this!
